function [] = import_new_motion()
    %% Initialize variables.
    filename = '../dtiprep/subjects';
    delimiter = '';

    %% Format string for each line of text:
    %   column1: text (%s)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Allocate imported array to column variable names
    subjects = dataArray{:, 1};

    %% Clear temporary variables
    clearvars filename delimiter formatSpec fileID dataArray ans;

    %% main
    nSubject=length(subjects);
    maxAngle=zeros(nSubject,3);
    maxTrans=zeros(nSubject,3);

    for i=1:nSubject
        file=sprintf('%s-motion',subjects{i});
        [rot,trans]=importMotion(file);
        file=sprintf('%s-motion.mat',subjects{i});
        save(file,'rot','trans');
        
        maxAngle(i,:)=max(abs(rot));
        maxTrans(i,:)=max(abs(trans));
    end
    
    system('mv [12]*n values/150908;mv mats/*.mat .');
end

function [rot,trans] = importMotion(filename, startRow, endRow)
    %IMPORTFILE Import numeric data from a text file as column vectors.
    %   [VARNAME1,VARNAME2,VARNAME3,VARNAME5,VARNAME6,VARNAME7] =
    %   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
    %   selection.
    %
    %   [VARNAME1,VARNAME2,VARNAME3,VARNAME5,VARNAME6,VARNAME7] =
    %   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
    %   through ENDROW of text file FILENAME.
    %
    % Example:
    %   [VarName1,VarName2,VarName3,VarName5,VarName6,VarName7] =
    %   importfile('motion',1, 84);
    %
    %    See also TEXTSCAN.

    % Auto-generated by MATLAB on 2013/11/04 15:34:18

    %% Initialize variables.
    delimiter = {'\t',' '};
    if nargin<=2
        startRow = 1;
        endRow = inf;
    end

    %% Format string for each line of text:
    %   column1-7: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%*s%f%f%f%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end

    %% Close the text file.
    fclose(fileID);

    %% Allocate imported array to column variable names
    rot = [dataArray{:, 1} dataArray{:, 2} dataArray{:, 3}];
    trans = [dataArray{:, 4} dataArray{:, 5} dataArray{:, 6}];
end
