function qsm(scanner, subjsFolder)
%% QSM processing pipeline
% Shengwei Zhang, RADC
% Prerequisites: MATLAB R2018b, FSL, STI suite v3.0

if nargin<2
    disp('Usage: qsm <scanner, mg or uc> <subjsFolder (abs. path)>')
    disp('e.g. : qsm mg $dataPath/$subjid')
    error('exiting...')
end

subjs=strsplit(subjsFolder,'/');
subjs=subjs{end};

if strcmp(scanner,'mg')
    voxelsize=[0.666667 0.666667 1.3];  % in unit mm
    TE1=4.65;                         % in unit msec.
elseif strcmp(scanner,'uc')
    voxelsize=[0.5 0.5 1.3];
    TE1=4.6;
else
    error('Scanner not defined')
end
deltaTE=4.5;                          % in unit msec.
B0=3;                                 % in unit Tesla

dim4=4; TE=sum(TE1:deltaTE:(TE1+deltaTE*(dim4-1)));

% SMVsize is around 12 -25 depending on your SNR requirement
% 25 should give higher SNR but longer computation time
% regarding vsharp, see https://www.ncbi.nlm.nih.gov/pubmed/21671269
smvsize=25;                           % V-SHARP radius
padsize=[12 12 12];                   % for qsm-star command
%% main
cd(subjsFolder);
% ref: STI_template.m in STI suite v3.0
fprintf('%s scan %s QSM processing pipeline starts  ...\n',upper(scanner),subjs)
tStart=tic;
system(['preproc ',scanner,' ',subjs]);

if strcmp(scanner,'mg')
    % find B0_vector
    system('gunzip qsm-mag.nii.gz');
    b0dir=get_orient('qsm-mag.nii');
    
    % load phase image
    phase=readFileNifti('phs.nii.gz');
    phase=phase.data;
    disp('Magnitude/phase image pair loaded.')
    
    % scale phase to 2pi range
    phase=double(phase);
    PhaseRange=max(phase(:))-min(phase(:))+1;
    
    phase=phase/PhaseRange*2*pi;
    %max(phase(:));
    disp('Image scaled to 2PI.')
else
    b0dir = [0 0 1];  % B0 vector, double check image header but it's the default
    % load real/imaginary pair and convert to magni/phase
    real=readFileNifti('real.nii.gz');
    real=real.data;
    
    imag=readFileNifti('imag.nii.gz');
    imag=imag.data;
    disp('Real/imaginary image pairs loaded.')
    
    Complexdata=real+1i*imag;
    magni=abs(Complexdata);
    phase=angle(Complexdata);
    ezsave_nii(magni,'magni.nii',[],voxelsize);
    ezsave_nii(phase,'phase.nii',[],voxelsize);
    disp('Conversion from real/imag to magni/phase done.')
end 
%% load brain mask generated by HD-BET & preproc script
mask=readFileNifti('mask-hdbet-ero2.nii.gz');
mask=double(mask.data);
disp('HD-BET mask loaded.')
%% unwrap phase image
disp('Starting unwrapping ...')
[UnwrappedPhase, Laplacian]=MRPhaseUnwrap(phase,'voxelsize',voxelsize);
disp('Done.')
%% background phase removal by V-SHARP
[TissuePhase]=V_SHARP(sum(UnwrappedPhase,4),mask,'voxelsize',voxelsize,'smvsize',smvsize);  
%% STAR-QSM recon
disp('Starting STAR-QSM ...')
QSMstar=QSM_star(TissuePhase,mask,'TE',TE,'B0',B0,'H',b0dir,'padsize',padsize,'voxelsize',voxelsize);
disp('Done.')
%% save variables
ezsave_nii(Laplacian,'Laplacian.nii',[],voxelsize);
ezsave_nii(UnwrappedPhase,'UnwrappedPhase.nii',[],voxelsize);
ezsave_nii(TissuePhase,'TissuePhase.nii',[],voxelsize);
ezsave_nii(QSMstar,'QSMstar.nii',[],voxelsize);
disp('Compressing nii files ...');
system('gzip TissuePhase.nii QSMstar.nii');
system(['postproc ',scanner]);

if strcmp(scanner,'mg')
    disp('Saving B0 vectors in b0dir.mat...')
    system('gunzip qsm-phs.nii.gz');
    b0dir=get_orient('qsm-phs.nii');
    save b0dir b0dir;
    system('rm qsm-phs.nii');
end

tElapsed=toc(tStart);
fprintf('Total elapsed time is %f seconds.\n',tElapsed)
