FROM ubuntu:18.04

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -qq \
    && apt-get install -yq --no-install-recommends \
           apt-utils \
           bc \
           ca-certificates \
           curl \
           dc \
           libopenblas-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && if [ ! -f "/opt/swe.sh" ]; then \
         echo '#!/usr/bin/env bash' >> /opt/swe.sh \
    &&   echo 'set -e' >> /opt/swe.sh \
    &&   echo 'export USER="${USER:=`whoami`}"' >> /opt/swe.sh;fi \
    && chmod 777 /opt && chmod a+s /opt && chmod a+x /opt/swe.sh

ENV FSLDIR="/opt/fsl-6.0.3" \
    PATH="/opt/fsl-6.0.3/bin:$PATH"
RUN echo "Downloading FSL ..." \
    && mkdir -p /opt/fsl-6.0.3 \
    && curl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.3-centos6_64.tar.gz \
    | tar -xz -C /opt/fsl-6.0.3 --strip-components 1 \
    && echo '. $FSLDIR/etc/fslconf/fsl.sh' >> /opt/swe.sh \
    && echo "Clean up unused FSL components ..." \
    && rm -r $FSLDIR/data $FSLDIR/lib $FSLDIR/src $FSLDIR/etc/xtract_data $FSLDIR/doc \
    && find $FSLDIR/bin -type l -delete \
    && rm $FSLDIR/bin/[a-r]* $FSLDIR/bin/[t-z]* $FSLDIR/bin/s[eilmptuy]* $FSLDIR/bin/[ARV]*

RUN echo 'cd /input;cogn=$1;metric=$2;seed=$3' >> /opt/swe.sh \
    && echo 'swe -i cogn-$cogn-skeletonized -o $metric-$cogn-SEED$seed -d design.mat -t design.con -s design.sub -m mean_FA_skeleton_mask --wb --vxl=11,12,13,14 --vxf=all_${metric}_skeletonised,all_${metric}_lag_skeletonised,all_wmh_skeletonised,all_wmh_lag_skeletonised --T2 -x -n 9 --seed=$seed' >> /opt/swe.sh

ENTRYPOINT ["/opt/swe.sh"]
