FROM ubuntu:16.04

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -qq \
    && apt-get install -yq --no-install-recommends \
           apt-utils \
           bc \
           ca-certificates \
           curl \
           dc \
           libopenblas-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && if [ ! -f "/opt/randomise.sh" ]; then \
         echo '#!/usr/bin/env bash' >> /opt/randomise.sh \
    &&   echo 'set -e' >> /opt/randomise.sh \
    &&   echo 'export USER="${USER:=`whoami`}"' >> /opt/randomise.sh;fi \
    && chmod 777 /opt && chmod a+s /opt && chmod a+x /opt/randomise.sh

ENV FSLDIR="/opt/fsl-6.0.3" \
    PATH="/opt/fsl-6.0.3/bin:$PATH"
RUN echo "Downloading FSL ..." \
    && mkdir -p /opt/fsl-6.0.3 \
    && curl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.3-centos6_64.tar.gz \
    | tar -xz -C /opt/fsl-6.0.3 --strip-components 1 \
    && echo '. $FSLDIR/etc/fslconf/fsl.sh' >> /opt/randomise.sh \
    && echo "Clean up unused FSL components ..." \
    && rm -rf $FSLDIR/bin/FSLeyes $FSLDIR/bin/fsl $FSLDIR/data $FSLDIR/lib $FSLDIR/src $FSLDIR/etc/xtract_data $FSLDIR/doc \
    && rm -f $FSLDIR/bin/[a-e]* $FSLDIR/bin/[A-V]* $FSLDIR/bin/[f-q]* $FSLDIR/bin/r[emou]* $FSLDIR/bin/[s-z]*

COPY randomise_openmp $FSLDIR/bin/

RUN echo "Generating start up script ..." \
    && echo 'cd /input;model=$1;in=$2;seednum=$3;iter=$4;mod=$5;is_dti=$6' >> /opt/randomise.sh \
    && echo 'if [ ${is_dti} = 'y' ] ;then' >> /opt/randomise.sh \
    && echo '  randomise_openmp --uncorrp --T2 -m mean_FA_skeleton_mask -d $model.mat -t $model.con -i $in-skeletonised --seed=$seednum -n $iter --vxl=5,6 --vxf=all_wmh_skeletonised.nii.gz,all_${mod}_skeletonised.nii.gz -o $model-$mod-$in-SEED$seednum' >> /opt/randomise.sh \
    && echo 'else' >> /opt/randomise.sh \
    && echo '  randomise_openmp --uncorrp -T -m mean_FA_skeleton_mask -d $model.mat -t $model.con -i $in-skeletonised --seed=$seednum -n $iter --vxl=5,6 --vxf=all_wmh_skeletonised.nii.gz,all_${mod}_skeletonised.nii.gz -o $model-$mod-$in-SEED$seednum' >> /opt/randomise.sh \
    && echo 'fi' >> /opt/randomise.sh

ENTRYPOINT ["/opt/randomise.sh"]
